import { useEffect, useState } from 'react';
import { ArrowRight, Check, Globe2, LoaderCircle, MessageCircle, RefreshCw, ShoppingCart, Sparkles, Store, X } from 'lucide-react';
import { getStoredBusiness } from './api';
import { generateImported3D, getCommerceSource, importCommerceWebsite, saveCommerceSource } from './commerceApi';

const WEBSITE_WHATSAPP='https://wa.me/923305315817?text='+encodeURIComponent('Hi, I found you through Ashes AI. I want a professional website for my business.');
const OPTIONS=[
 ['ashes','I need a website','Talk directly on WhatsApp and get a complete website built for your business.',Store],
 ['website','Existing website','Keep your current website and use Ashes as the 3D/AR layer.',Globe2],
 ['shopify','Shopify','Connect your Shopify catalog to the Ashes experience.',ShoppingCart],
 ['woocommerce','WooCommerce','Use your WooCommerce store as the commerce source.',ShoppingCart],
 ['custom','Custom ecommerce','Route customers back into your own commerce system.',Globe2],
];
export default function CommerceSourceManager(){
 const[open,setOpen]=useState(false),[business,setBusiness]=useState(()=>getStoredBusiness()),[source,setSource]=useState(null),[saving,setSaving]=useState(false),[importing,setImporting]=useState(false),[generating3d,setGenerating3d]=useState(false),[result,setResult]=useState(null),[generationResult,setGenerationResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{const show=()=>{setBusiness(getStoredBusiness());setOpen(true)};window.addEventListener('ashes:open-commerce',show);return()=>window.removeEventListener('ashes:open-commerce',show)},[]);
 useEffect(()=>{if(!open||!business?.slug)return;setError('');getCommerceSource(business.slug).then(setSource).catch(e=>setError(e.message))},[open,business?.slug]);
 if(!open)return null;
 const form=source||{source_type:'ashes',website_url:'',checkout_url:'',sync_enabled:false,external_checkout:false,store_label:'Ashes'};const patch=v=>setSource({...form,...v});
 const save=async()=>{setSaving(true);setError('');try{setSource(await saveCommerceSource(business.slug,form))}catch(e){setError(e.message)}finally{setSaving(false)}};
 const runImport=async()=>{if(!form.website_url)return setError('Add the merchant website URL first.');setImporting(true);setError('');setResult(null);setGenerationResult(null);try{setResult(await importCommerceWebsite(business.slug,form.website_url,14))}catch(e){setError(e.message)}finally{setImporting(false)}};
 const runGenerate3D=async()=>{if(!business?.slug)return;setGenerating3d(true);setError('');setGenerationResult(null);try{setGenerationResult(await generateImported3D(business.slug,[],12))}catch(e){setError(e.message)}finally{setGenerating3d(false)}};
 return <div className="commerce-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="commerce-studio"><header><div><span>ASHES COMMERCE CONNECTION</span><h2>Connect the store you have. Build one if you don’t.</h2><p>Ashes becomes the 3D/AR sales layer for an existing store. Businesses without a website can contact our web-development team directly.</p></div><button onClick={()=>setOpen(false)}><X size={20}/></button></header>
 {!source?<div className="commerce-loading"><LoaderCircle className="spin-icon"/> Loading commerce settings…</div>:<div className="commerce-layout"><div className="commerce-main"><div className="commerce-option-grid">{OPTIONS.map(([key,name,text,Icon])=><button key={key} className={form.source_type===key?'active':''} onClick={()=>patch({source_type:key,external_checkout:key!=='ashes'})}><Icon size={21}/><strong>{name}</strong><span>{text}</span>{form.source_type===key&&<i><Check size={12}/></i>}</button>)}</div>
 {form.source_type==='ashes'?<section className="ashes-store-upsell"><Sparkles size={24}/><div><span>NEED A WEBSITE?</span><h3>Get your complete business website built for you.</h3><p>Website design, storefront, products and Ashes integration are quoted separately. Speak directly on WhatsApp — no confusing automated website package.</p><a className="website-whatsapp-cta" href={WEBSITE_WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={18}/> WhatsApp 0330 5315817 <ArrowRight size={16}/></a></div></section>:<><section className="commerce-fields"><label><span>Website / store URL</span><input value={form.website_url||''} onChange={e=>patch({website_url:e.target.value})} placeholder="https://merchant.com"/></label><label><span>Cart or checkout URL</span><input value={form.checkout_url||''} onChange={e=>patch({checkout_url:e.target.value})} placeholder="https://merchant.com/cart"/><small>Customers enjoy the Ashes 3D/AR experience first, then continue to the business's own checkout.</small></label><div className="commerce-switch-row"><label><input type="checkbox" checked={!!form.external_checkout} onChange={e=>patch({external_checkout:e.target.checked})}/><span><b>Use merchant checkout</b><small>Orders and payments continue through their existing website.</small></span></label><label><input type="checkbox" checked={!!form.sync_enabled} onChange={e=>patch({sync_enabled:e.target.checked})}/><span><b>Catalog sync</b><small>Keep this commerce source available for product synchronization.</small></span></label></div></section><section className="commerce-importer"><div><span>AUTHORIZED WEBSITE IMPORT</span><h3>Turn the existing website into an Ashes catalog.</h3><p>Import product information as drafts, review it, then queue those drafts for one-by-one 3D generation.</p></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button disabled={importing} onClick={runImport}>{importing?<><LoaderCircle className="spin-icon"/> Importing…</>:<><RefreshCw size={16}/> Import website catalog</>}</button><button disabled={generating3d} onClick={runGenerate3D}>{generating3d?<><LoaderCircle className="spin-icon"/> Queueing 3D…</>:<><Sparkles size={16}/> Generate imported products</>}</button></div></section></>}
 {result&&<div className="commerce-import-result"><Check size={18}/><div><strong>{result.created} Ashes drafts created</strong><span>{result.found} products detected. Product image sets are saved for 3D generation.</span></div></div>}{generationResult&&<div className="commerce-import-result"><Check size={18}/><div><strong>{generationResult.queued} products queued for 3D</strong><span>{generationResult.queued?`Ashes is processing them one by one. ${generationResult.items?.filter(x=>x.mode==='multi-image').length||0} have 3+ views for multidiffusion.`:'No eligible imported drafts were ready to queue.'}</span></div></div>}{error&&<div className="form-error">{error}</div>}</div><aside className="commerce-preview"><span>HOW IT WORKS</span><div className="commerce-route-step active"><i>1</i><div><strong>Customer scans QR</strong><small>Ashes opens the product in 3D/AR</small></div></div><b>↓</b><div className="commerce-route-step active"><i>2</i><div><strong>Explore & configure</strong><small>Premium Ashes customer experience</small></div></div><b>↓</b><div className="commerce-route-step"><i>3</i><div><strong>{form.source_type==='ashes'?'Get a website':'Merchant checkout'}</strong><small>{form.source_type==='ashes'?'Talk directly to us on WhatsApp':'Order/payment continues on their store'}</small></div></div><div className="commerce-route-badge">{form.source_type==='ashes'?'WEBSITE SERVICE':'COMMERCE LAYER'}</div></aside></div>}
 <footer><div><span>Business setup</span><strong>{form.source_type==='ashes'?'Website needed · contact us directly':'Ashes 3D/AR + existing commerce'}</strong></div><button className="secondary-btn" onClick={()=>setOpen(false)}>Close</button>{form.source_type!=='ashes'&&<button className="primary-btn" disabled={saving||!source} onClick={save}>{saving?'Saving…':'Save commerce source'} <ArrowRight size={16}/></button>}</footer></section></div>;
}
