name = "Ashes"
client_id = "REPLACE_WITH_SHOPIFY_CLIENT_ID"
application_url = "https://REPLACE_WITH_YOUR_APP_URL"
embedded = true

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://REPLACE_WITH_YOUR_APP_URL/api/shopify/auth/callback"
]

[webhooks]
api_version = "2026-07"

[pos]
embedded = false
